### ISSUE TITLE
Error to-gantt-view.ejs

### ISSUE THREAD

**Issue by tangry** [iondv/pm-gov-ru#1]
Добрый день. 
Установил систему на CentOS 7.7
При нажатии на название проекта в разделе Проекты получаю следующую ошибку:

Error: /root/pm-gov-ru/applications/pm-gov-ru/templates/registry/to-gantt-view.ejs:374
    372|         enctype="multipart/form-data" data-options="<%= JSON.stringify(options) %>">
    373|     <div class="panel-body">
 >> 374|       <input type="hidden" name="$action" value="">
    375|       <div class="tabs">
    376|         <%- partial(resolveTpl('groups/_tabs'), {
    377|           tabs: form.tabs

/root/pm-gov-ru/modules/registry/view/default/templates/groups/_default.ejs:6
    4| <div id='tabs-<%= numb %>' class="tab-pane <%- numb === 0 ? 'active' : '' %>">
    5|   <% fields.forEach((prop, i) => { %>
 >> 6|     <%- partial('./_default_prop', {prop, item, tabIndex: numb, fieldIndex: i}) %>
    7|   <% }); %>
    8| </div>

/root/pm-gov-ru/modules/registry/view/default/templates/groups/_default_prop.ejs:15
    13| if (tpl) {
    14| %>
 >> 15| <%-partial(resolveTpl(tpl), {
    16|   id: FieldId,
    17|   prop: itemProperty,
    18|   field: prop,

Could not find partial file-collection
    at Object.partial (/root/pm-gov-ru/node_modules/ejs-locals/index.js:311:11)
    at eval (eval at exports.compile (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:43:38)
    at eval (eval at exports.compile (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:60:21)
    at /root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:250:15
    at Object.exports.render (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:288:13)
    at render (/root/pm-gov-ru/node_modules/ejs-locals/index.js:334:20)
    at Object.partial (/root/pm-gov-ru/node_modules/ejs-locals/index.js:376:12)
    at fields.forEach (eval at exports.compile (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:30:330)
    at Array.forEach (<anonymous>)
    at eval (eval at exports.compile (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:30:266)
    at eval (eval at exports.compile (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:30:461)
    at /root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:250:15
    at Object.exports.render (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:288:13)
    at render (/root/pm-gov-ru/node_modules/ejs-locals/index.js:334:20)
    at Object.partial (/root/pm-gov-ru/node_modules/ejs-locals/index.js:376:12)
    at eval (eval at exports.compile (/root/pm-gov-ru/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:105:176)

Из-за чего это может происходить?

Спасибо.

**Comment by akumidv** [comment]
Добрый день! Спасибо за вопрос. Ошибка происходит на форме представления объекта проекта при генерации сводного кастомизированного шаблона. Правильно ли предполагаю что по ссылке подобной https://pm-gov-ru.iondv.com/registry/pm-gov-ru@project, когда со списка проектов - открываете проект?

Сообщение об ошибке говорит, что не найдено представление "file-collection" - оно подключается в форме представления проекта для коллекции файлов https://github.com/iondv/pm-gov-ru/blob/master/views/project/item.json 

Это представление задается в приложении расширения viewlib https://github.com/iondv/viewlib . Установили ли вы его в папку applications? Оно указано как необходимое в https://github.com/iondv/pm-gov-ru/blob/master/package.json свойство 
```
 "ionMetaDependencies": {
    "viewlib": "0.12.4"
  }, 
```
После установки - нужно провести инициализацию конфигурации `node bin/setup /viewlib`, если у вас конфигурации хранятся в СУБД (параметр deploy.mode=db в файле config/setup.ini) и перезапустить. Если деплой из файлов, т.е. без этого параметра - то просто перезапустить.

**Comment by akumidv** [comment]
Попробуйте собрать через [сборщик](https://github.com/iondv/iondv-app/blob/master/README_RU.md) 
```
bash <(curl -sL https://raw.githubusercontent.com/iondv/iondv-app/master/iondv-app) \
  -t git -p /workspace -m localhost:27017 pm-gov-ru
```
Он соберет приложение в папке /workspace/pm-gov-ru и запустит его. СУБД Mongodb в этом примере запущена по адресу  localhost:27017
